### ISSUE TITLE
Install leads extension on your environment

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/leads#14]
## 1. Read about MySaaS extensions:
https://github.com/leandrosardi/mysaas/blob/main/docu/12.extensibility.md

## 2. Install the Leads extension in you MySaaS project, 
by following the steps in this tutorial:
https://github.com/leandrosardi/leads#leads

## 3. Access the pre-built screens of the leads app.
Check out the screens. Get familiarized.
http://127.0.0.1/leads/landing
http://127.0.0.1/leads/step1
http://127.0.0.1/leads/step2
http://127.0.0.1/leads/tripwire
http://127.0.0.1/leads/results
http://127.0.0.1/leads/search
http://127.0.0.1/leads/saved_searches
http://127.0.0.1/leads/exports

Add a comment with attachments of the screens working in your environment.

**Comment by hamaadrana** [comment]
![1](https://user-images.githubusercontent.com/40526746/175259215-00b3640d-e44e-446e-88ab-5978422107f6.png)
![exports](https://user-images.githubusercontent.com/40526746/175259228-dc225d30-d66b-456b-b1a3-1493fa02783a.png)
![results](https://user-images.githubusercontent.com/40526746/175259238-930c7995-7175-4856-b0d0-9d0396ac35f4.png)
![saved_searched](https://user-images.githubusercontent.com/40526746/175259243-fa7f524e-3231-4a2a-b1b4-2776b2a2f6e1.png)
![search](https://user-images.githubusercontent.com/40526746/175259254-2efb7204-e76b-4920-891a-d5459e943db8.png)
![step1](https://user-images.githubusercontent.com/40526746/175259262-80e23241-0760-4cb6-a4e5-7989f6ca8639.png)
![step2](https://user-images.githubusercontent.com/40526746/175259267-fe718c84-b042-4af0-b6b3-a8122d682bdf.png)
![tripwire](https://user-images.githubusercontent.com/40526746/175259272-47617bc9-9426-4c49-a188-b9f6be9a9a58.png)

**Comment by leandrosardi** [comment]
Well done.

Issue closed.
