### ISSUE TITLE
Write the sql script for creating the schema.

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/leads#9]
- I already have an `.sql` file for creating the schema for our **leads** app.

- But such an `.sql` file has been written for SQLServer.

- You should convert to from SQLServer to PostgreSQL.

- **Also, feel free to review the whole script, and suggest any modificaiton that you consider (that is very important that you start taking desgin decisions).**
Just add a comment in this issue with your sufferences.

- Your `.sql` script should follow the guidelines of [blackstack-deployer](https://github.com/leandrosardi/blackstack-deployer):
[Reprocessing Database Updates](https://github.com/leandrosardi/blackstack-deployer#5-reprocessing-database-updates)

- Here is the current `.sql` file:
[https://drive.google.com/file/d/1owbtTLzS76pHIjFD67j96GBTr3uyimxf/view?usp=sharing](https://drive.google.com/file/d/1owbtTLzS76pHIjFD67j96GBTr3uyimxf/view?usp=sharing).
We have a diagram either:
[https://drive.google.com/file/d/1i8WXo0iUflhWkByn87G4oWTA5RtaBQEt/view?usp=sharing](https://drive.google.com/file/d/1i8WXo0iUflhWkByn87G4oWTA5RtaBQEt/view?usp=sharing).

- Add a comment into this issue, with your `.sql` file attached.

**Comment by leandrosardi** [comment]
@hamaadrana, 

1. ID fields must be `uuid` type.
Example:
```sql
-- possible countries assigned to a user.
CREATE TABLE IF NOT EXISTS country(
	id uuid NOT NULL PRIMARY KEY,
	code varchar(500) NOT NULL,
	name varchar(500) NOT NULL
);
```

**Comment by leandrosardi** [comment]
Add your .sql script to the sql folder of the leads extension (~/code/mysaas/extensions/leads/sql).

The filename of your .sql file must follow the guidelines of our BlackStack Deployer:
https://github.com/leandrosardi/blackstack-deployer#4-running-database-updates

Push it to the repository.

```bash
cd ~/code/mysaas/extensions/myleads
git add *.sql
git commit -m "database schema"
git push
```

Note that you will push to the leads repo. Not to the mysaas repo.

**Comment by leandrosardi** [comment]
CORRECTION REQUEST

I am getting an error when I execute your script `20220621.1.transactions.sql`.

1. Please push correction.
2. Please test the other `.sql` scripts also.

![image](https://user-images.githubusercontent.com/55877846/175124264-b278d3ce-bbf1-400d-b893-aefd32c4e50e.png)

**Comment by hamaadrana** [comment]
The error says **"relation User does not exists"**. You asked me to remove the script for Users' table creation because it's already present in mysaas. So do we need to add?

**Comment by leandrosardi** [comment]
> The error says **"relation User does not exists"**. You asked me to remove the script for Users' table creation because it's already present in mysaas. So do we need to add?

There is a `user` table already installed by MySaaS.

You have to reference such a table.

Your glitch is that you are writing `users` instead `user`.

BTW, IDK if there are other glitches in your scripts.

You should run them in your local environment for testing.

**Comment by leandrosardi** [comment]
Done.
